name: context testing
on: issues
jobs:
    dump_context_to_log:
        runs-on: ubuntu-latest
        steps:
            - name: Dump Github context
              env: 
                GITHUB_CONTEXT: ${{toJson(github.event)}}
              run: echo "$GITHUB_CONTEXT"
            - name: Dump Job Context
              env:
                JOB_CONTEXT: ${{toJson(job.event)}} 
              run: echo "$JOB_CONTEXT"
            - name: Dump Step Context
              run: echo "${{toJson(steps)}}"
